### ISSUE TITLE
modals don´t get triggered

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/persistence#5]
Creating Modal as usual with PersistentCustomID as custom_id.
Modal show up as expected.
By submitting the modal it stucks.

Code:
```
custom_id = PersistentCustomID(
        cipher=bot,
        tag="team_edit",
        package=team_id,
    )

modal = interactions.Modal(
        title="Änder Team",
        custom_id=str(custom_id),
        components=[
            di.TextInput(
                style=interactions.TextStyleType.SHORT,
                label="Kurzer Name.",
                custom_id="team_shortname",
                value=team_shortname,
                min_length=1,
                max_length=10,
                required=True
            ),
            di.TextInput(
                style=interactions.TextStyleType.SHORT,
                label="Langer Name.",
                custom_id="team_longname",
                value=team_longname,
                min_length=1,
                max_length=100,
                required=True
            ),
        ]
    )
await ctx.popup(modal=modal)

@bot.persistent_modal("team_edit")
async def editteam_modal(ctx: interactions.ComponentContext, package: str, team_shortname: str, team_longname: str):
```

Error in Console: (by starting bot)
```
Traceback (most recent call last):
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Jan\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Jan\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\Jan\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Jan\Documents\GitHub\TBG_Bot\bot\bot.py", line 1378, in <module>
    async def editteam_modal(ctx: di.ComponentContext, package: str, team_shortname: str, team_longname: str):
  File "c:\Users\Jan\Documents\GitHub\TBG_Bot\.venv\lib\site-packages\interactions\ext\persistence\client.py", line 28, in inner
    self.persistence.modal(tag, use_kwargs)(coro)
  File "c:\Users\Jan\Documents\GitHub\TBG_Bot\.venv\lib\site-packages\interactions\ext\persistence\persistence.py", line 69, in inner
    logging.debug("Registered persistent modal:", tag)
Message: 'Registered persistent modal:'
Arguments: ('team_edit',)
```

Log Debug: (when submit modal)

```
DEBUG - 30.06.2022 11:20:31: INTERACTION_CREATE: {'version': 1, 'type': 5, 'token': '...', 'member': {'user': {'username': 'Donbur', 'public_flags': 0, 'id': '290948271566880768', 'discriminator': '4156', 'avatar_decoration': None, 'avatar': '...'}, 'roles': [...], 'premium_since': None, 'permissions': '4398046511103', 'pending': False, 'nick': None, 'mute': False, 'joined_at': '...', 'is_pending': False, 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'avatar': None}, 'locale': 'de', 'id': '991996649952006144', 'guild_locale': 'en-US', 'guild_id': '925837829366513674', 'data': {'custom_id': 'p~RwRVub0:e~.Wji/', 'components': [{'type': 1, 'components': [{'value': 'shortnametext', 'type': 4, 'custom_id': 'team_shortname'}]}, {'type': 1, 'components': [{'value': 'longnametext', 'type': 4, 'custom_id': 'team_longname'}]}]}, 'channel_id': '925837830779973638', 'application_id': '925700101387726858', 'app_permissions': '1089146842817'}
DEBUG - 30.06.2022 11:20:31: Attribute app_permissions is missing from the CommandContext data model, skipping.
DEBUG - 30.06.2022 11:20:31: Attribute avatar_decoration is missing from the User data model, skipping.
DEBUG - 30.06.2022 11:20:31: DISPATCH: <bound method Persistence.on_modal of <interactions.ext.persistence.persistence.Persistence object at 0x000001E7705AFBB0>>
```

**Comment by Dworv** [comment]
Fixed in version 2.1.0
